networks:
  mediaapps_default:
    name: mediaapps_default
    ipam:
      config:
        - subnet: 172.40.0.0/24
        
services:
  # Commented out Jellyfin service; Currently using Plex for media server needs.
  # jellyfin:
  #   container_name: jellyfin
  #   image: lscr.io/linuxserver/jellyfin:latest
  #   ports:
  #     - 8096:8096
  #     - 8920:8920 #optional
  #     - 7359:7359/udp #optional
  #     - 1900:1900/udp #optional
  #   networks:
  #     mediaapps_default:
  #       ipv4_address: 172.40.0.2
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_SERVER_URL} #optional
  #   volumes:
  #     - /path/to/jellyfin/library:/config
  #     - /path/to/tvseries:/data/tvshows
  #     - /path/to/movies:/data/movies
  #   healthcheck:
  #     test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
  #     start_period: 20s
  #     timeout: 3s
  #     interval: 15s
  #     retries: 3
  #   restart: unless-stopped

  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:latest
    ports:
      - 8181:8181
    networks:
      mediaapps_default:
        ipv4_address: 172.40.0.3
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/docker/mediaapps/config/tautulli:/config
    restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/fallenbagel/jellyseerr:latest
    init: true
    ports:
      - 5055:5055
    networks:
      mediaapps_default:
        ipv4_address: 172.40.0.4
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/docker/mediaapps/config/jellyseerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped

  stash:
    container_name: stash
    image: stashapp/stash:latest
    ## the container's port must be the same with the STASH_PORT in the environment section
    ports:
      - "9999:9999"
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    networks:
      mediaapps_default:
        ipv4_address: 172.40.0.5
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash
      ## The left part is the path on your host, the right part is the path in the stash container.

      ## Keep configs, scrapers, and plugins here.
      - ./stash/config:/root/.stash
      ## Point this at your collection.
      ## The left side is where your collection is on your host, the right side is where it will be in stash.
      - /mnt/data/media/adult:/data
      ## This is where your stash's metadata lives
      - ./stash/metadata:/metadata
      ## Any other cache content.
      - ./cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - ./stash/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - ./stash/generated:/generated
    restart: unless-stopped